# Generated by Django 2.1.3 on 2018-11-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='input_type',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='item',
            name='resolution',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='item',
            name='serial_number',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
