# Generated by Django 2.1.3 on 2018-11-03 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20181103_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament_Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_players',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='blank', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='open_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 3, 17, 11, 13, 182040)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 3, 17, 11, 17, 860129)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament_players',
            name='tournaments',
            field=models.ManyToManyField(to='inventory.Tournament'),
        ),
    ]
