# Generated by Django 2.1.3 on 2018-11-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20181103_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament_players',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='tournament',
            name='m_points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament_players',
            name='last_name',
            field=models.CharField(default=' ', max_length=128),
            preserve_default=False,
        ),
    ]
