# Generated by Django 2.1.2 on 2018-11-30 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20181103_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('badge_number', models.CharField(max_length=7)),
                ('tournaments', models.ManyToManyField(to='inventory.Tournament')),
            ],
        ),
        migrations.RemoveField(
            model_name='tournament_players',
            name='tournaments',
        ),
        migrations.DeleteModel(
            name='Tournament_Players',
        ),
    ]
