# Generated by Django 2.2.6 on 2019-12-27 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20190102_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='printed',
            field=models.BooleanField(default=False),
        ),
    ]
