# Generated by Django 2.1.5 on 2020-01-02 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_tournament_printed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='m_points',
            field=models.IntegerField(null=True),
        ),
    ]
