# Generated by Django 2.1.5 on 2020-01-02 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20200101_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='m_points',
            field=models.CharField(blank=True, default='', max_length=25),
            preserve_default=False,
        ),
    ]
