# Generated by Django 4.1.4 on 2022-12-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_tournament_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='department',
            field=models.CharField(choices=[('Consoles', 'Consoles'), ('Arcade', 'Arcade'), ('Indie-Arcade', 'Indie-Arcade'), ('MIVS', 'MIVS')], max_length=64),
        ),
    ]
