# Generated by Django 4.1.4 on 2022-12-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_tournament_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='custom_m_points',
            field=models.BooleanField(default=False),
        ),
    ]
