# Generated by Django 4.1.4 on 2022-12-30 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_tournament_custom_m_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='department',
            field=models.CharField(choices=[('Consoles', 'Consoles'), ('Arcade', 'Arcade'), ('Indie-Arcade', 'Indie-Arcade'), ('MIVS', 'MIVS'), ('Large Tournament Collider', 'LTC')], max_length=64),
        ),
    ]
