# Generated by Django 4.1.4 on 2022-12-31 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_tournament_info_only_tournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='team_tournament',
            field=models.IntegerField(default=1),
        ),
    ]
