# Generated by Django 4.1.4 on 2022-12-31 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_rename_team_tournament_tournament_team_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentteam',
            name='players',
            field=models.ManyToManyField(to='inventory.tournamentplayer'),
        ),
        migrations.AddField(
            model_name='tournamentteam',
            name='tournament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.tournament'),
            preserve_default=False,
        ),
    ]
