# Generated by Django 2.1.5 on 2023-04-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_tournamentteam_players_tournamentteam_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='challonge_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
