# Generated by Django 2.1.5 on 2023-04-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_tournament_challonge_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='challonge_id',
            field=models.IntegerField(null=True),
        ),
    ]
