# Generated by Django 2.1.5 on 2023-04-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_auto_20230422_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentplayer',
            name='challonge_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='challonge_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
