# Generated by Django 4.1.4 on 2024-01-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_auto_20230422_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentplayer',
            name='challonge_id',
        ),
        migrations.AddField(
            model_name='tournamentplayer',
            name='challonge_ids',
            field=models.TextField(default='{}'),
        ),
    ]
