# Generated by Django 4.1.4 on 2024-01-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_remove_tournamentplayer_challonge_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='allow_waitlist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='challonge_url',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='tournamentteam',
            name='challonge_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
