# Generated by Django 4.1.4 on 2024-01-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_tournament_allow_waitlist_tournament_challonge_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='allow_waitlist',
        ),
        migrations.AddField(
            model_name='tournament',
            name='waitlist_cap',
            field=models.IntegerField(default=0),
        ),
    ]
